name: GitHub Actions Build and Deploy Demo
on:
  pull_request:
    types: [opened, reopened]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
